export const ROLES = {
  ADMIN: 'admin',
  ANALYST: 'analyst',
  OPERATOR: 'operator',
};

export const ROLE_HIERARCHY = {
  [ROLES.ADMIN]: [ROLES.ADMIN, ROLES.ANALYST, ROLES.OPERATOR],
  [ROLES.ANALYST]: [ROLES.ANALYST, ROLES.OPERATOR],
  [ROLES.OPERATOR]: [ROLES.OPERATOR],
};