version: '3.8'

include:
  - path: docker-compose-postgres.yml
  - path: docker-compose-keycloak.yml
  - path: docker-compose-app.yml

networks:
  drone-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1