services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.7
    container_name: drone_keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}  # Используем основную БД
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_PORT: 8090
    command: start-dev
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8090:8090"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      drone-network:
        ipv4_address: 172.20.0.30
    restart: unless-stopped
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:8090/health/ready"]
#      interval: 10s
#      timeout: 5s
#      retries: 10
#      start_period: 30s

volumes:
  keycloak_data:

